title: Watcharapong Wongkaew
position: Graduate/ Ph. D. Student
affiliation: Chulalongkorn University Transportation Institute
email: watcharapong.w@chula.ac.th
keywords: minimal academic
google_scholar: https://scholar.google.com/
github_link: https://github.com/wattwong103/
linkedin: https://www.linkedin.com/in/w-wongkaew/
cv_link: 
avatar: ./assets/img/avatar2.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Strata Academic is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic
